### ISSUE TITLE
Fix mem leaks

### ISSUE THREAD

**Issue by bshastry** [bshastry/ecdsa-sign-verify#2]
Fix memory leaks associated with test harness. I'm not sure if they are harness bugs or openssl bugs. If the latter, we should report upstream.

**Comment by viniul** [comment]
Do the leaks occur when `FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION` is set or not? If they occur if it is not set, then I believe 
`    printf("r: %s\n", BN_bn2hex(sig_r));
    printf("s: %s\n", BN_bn2hex(sig_s));`

might be the source of the error. We need to free the created strings.

**Comment by bshastry** [comment]
Thank you @viniul :-)

Your PR #5 fixes the mem leak as well.
