### ISSUE TITLE
Fix wrong signature assignment

### ISSUE THREAD

**Issue by viniul** [bshastry/ecdsa-sign-verify#4]
I suspect the current harness  has a bug. It calls: 

`signMessageDigest(signature, (uint8_t *)&digest[0], key, message, Size);`

and then:
`assert(signature);`

But in `signMessageDigest` signature gets assigned another value:

`signature = ECDSA_do_sign(digest, 32, key);`

But here the pointer gets a new value assigned, not something to pointer is pointing to. This means the after the call of `signMessageDigest` `signature` will be `null` again. This can be verified by entering this print statement:

`fprintf(stderr, "Signature %p \n", signature);`

after
`    ECDSA_SIG_get0(signature, &sig_r, &sig_s);
`

and also after the call of `signMessageDigest`.

I believe fixing this will also fix a memory leak

**Comment by bshastry** [comment]
Thank you @viniul 

Note to future self: https://stackoverflow.com/a/30519731
